name: Swift-iOS-Build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Swift environment
      - name: Set up Swift
        uses: apple/setup-swift@v2
        with:
          swift-version: '5.7' # Use the Swift version compatible with your project

      # Install CocoaPods dependencies
      - run: pod install
        working-directory: ios

      # Build the Swift project for iOS
      - run: xcodebuild -workspace ios/YourWorkspace.xcworkspace -scheme YourScheme -sdk iphoneos -configuration Release archive -archivePath build/YourApp.xcarchive
        working-directory: ios

      # Create .ipa file
      - run: xcodebuild -exportArchive -archivePath build/YourApp.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath build/ios/ipa
        working-directory: ios

      # Zip output
      - name: Zip output
        run: zip -qq -r -9 YourApp.ipa build/ios/ipa
        working-directory: build/ios/ipa

      # Upload binaries to release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/ipa/YourApp.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"

